### ISSUE TITLE
For reproducibility, repo should contain modifications to make-demo.sh, not the generated result

### ISSUE THREAD

**Issue by mikehardy** [khat33b/rn-androidx-demo#1]
I will not be able to diagnose it well based on the results of the script

We need to see the changes to make-demo.sh required to create a failure

For instance, what version of the react-native-cli are you using? what template command did you use? with what react-native tags etc?

All the commands required to go from nothing to a failure are what we need to see

**Comment by mikehardy** [comment]
@khat33b not sure if you have notifications on for your repo or not so I’m tagging just in case ;-)

**Comment by khat33b** [comment]
@mikehardy I have notifications turned on. I have actually left for home so I'll send you info tomorrow.

**Comment by mikehardy** [comment]
sounds good - just to be super specific since we're on opposing time zones, so we don't miss a chance, the whole rn-androidx-demo repo is actually just to hold that make-demo.sh script, so I'd remove every other thing and just modify make-demo.sh, then commit that. We'll see what blows up and try to fix it! :-) cheers

**Comment by khat33b** [comment]
@mikehardy I have added the shell file and removed the others.

**Comment by khat33b** [comment]
@mikehardy Run the script and then on running `react-native run-android`, I am getting **Could not resolve** errors for AndroidX libraries in the linked projects.

**Comment by mikehardy** [comment]
thank you! I’ll check

**Comment by khat33b** [comment]
I fixed the errors manually and it worked out OK. But my worrk project has that error `library "libjsc.so" not found.` I have not been able to solve that.

**Comment by mikehardy** [comment]
If your goal is an AndroidX app, the problem is your init call. Do this per the release docs for RN0.60 RC2 react-native init rnandroidxdemo --version react-native@next and remove your npm i react-native call

Also, comment out the reverse test at the end, and for me anyway it seems to work.

Your libjsc thing is project-specific - no ideas there, sorry

**Comment by khat33b** [comment]
I had done that the second time but I got the same issues. It seems that react-native-maps did not convert to AndroidX properly and FBSDK requires a parameter in its constructor. So when it was auto generated, it gave an error.

**Comment by mikehardy** [comment]
Oh hmm - I had commented out a few dependencies to speed up the cycle so maybe I missed those two. Can you think of any others specifically? I’ll check them specifically

**Comment by mikehardy** [comment]
FBSDK constructor parameter is handled with a sed call in the script FWIW, but maps, I dunno

**Comment by khat33b** [comment]
Those two caused the bulk of the problems. other were successful.

Could you please give some hints as to how I would solve the libjsc issue? I just can't figure it out and none of the answerss in SO fix my problem.

**Comment by mikehardy** [comment]
no idea unfortunately never seen it. In cases like that I typically bisect. You mention it’s a work app so you can’t divulge I’d suppose, but I’d take something like make-demo.sh but with all your dependencies as the things to fetch + link. Make sure you can reproduce. Then binary search through until you can break it or fix it with one dependency change, then pursue that library ?

Or perhaps you’ll learn that it was something about project construction at which point take the new recipe to make a fresh skeleton at the native layer and hang your app code back on it

**Comment by khat33b** [comment]
OK. Thanks for the help.

**Comment by mikehardy** [comment]
Here’s what you need to avoid hand-hacking react-native-fbsdk (or anything that takes a parameter) in the new “auto-linking” world of RN0.60:

```json
module.exports = {
  'react-native-fbsdk': {
    platforms: {android: {packageInstance: "new RNFBSDKPackage(com.facebook.CallbackManager.Factory.create())"}}
  }
}
```

https://github.com/react-native-community/cli/blob/master/docs/dependencies.md#platformsandroidpackageinstance

**Comment by mikehardy** [comment]
Here’s what you need for react-native-maps https://github.com/react-native-community/react-native-maps/pull/2927 - maybe they’ll accept it - **update** it was accepted but is not released yet.

So FBSDK needs a config thing for the new auto-linking (either the library needs a change - they’re aware of that upstream now, or a local config can be done - which is what I’m doing in my test suite now) and react-native-maps will work if you take my PR branch.

**Comment by khat33b** [comment]
I solved my `library "libjsc.so" not found` error. I had to create a new project and then added the dependencies and the JS source and that worked.
